#!/bin/bash

echo "🚀 Creating GitHub Repository for Invoice SaaS"
echo "=============================================="
echo ""
echo "Follow these steps to create your GitHub repository:"
echo ""
echo "1. Go to: https://github.com/new"
echo "2. Repository name: invoice-saas"
echo "3. Description: Cloud-native Invoice SaaS Application with React and AWS"
echo "4. Set to Public (or Private)"
echo "5. Don't initialize with README (we already have one)"
echo "6. Click 'Create repository'"
echo ""
echo "Then run these commands:"
echo ""
echo "git remote add origin https://github.com/YOUR_USERNAME/invoice-saas.git"
echo "git branch -M main"
echo "git push -u origin main"
echo ""
echo "Replace YOUR_USERNAME with your GitHub username"
echo ""
echo "🎉 Your repository will be live at:"
echo "https://github.com/YOUR_USERNAME/invoice-saas"